import type { MarketPricingResult, MarketConfig } from '@/engine/markets/types';

/**
 * Generate a plain-text summary for clipboard sharing.
 */
export function generateSummaryText(result: MarketPricingResult, market: MarketConfig): string {
  const sym = market.currency.symbol;
  const fmt = (v: number) => `${sym}${v.toFixed(2)}`;

  const lines: string[] = [
    `Wine Pricing Studio — ${market.flag} ${market.name}`,
    '─'.repeat(50),
    '',
    `Product: ${fmt(result.inputs.costPerBottle)} / bottle × ${result.inputs.casePack} btl = ${fmt(result.summary.baseCostCase)} / case`,
  ];

  if (market.currency.needsConversion) {
    lines.push(
      `FX Rate: ${result.assumptions.effectiveRate.toFixed(4)} (${market.currency.source} → ${market.currency.target})`,
    );
  }

  lines.push('');
  lines.push('Pricing Waterfall');
  lines.push('─'.repeat(50));

  for (const step of result.waterfall) {
    const label = step.label.padEnd(28);
    lines.push(`  ${label} ${fmt(step.perCase).padStart(12)}  (${fmt(step.perBottle)} / btl)`);
  }

  lines.push('─'.repeat(50));
  lines.push('');
  lines.push('Summary');
  lines.push(`  Landed Cost:     ${fmt(result.summary.landedCase)} / case`);
  lines.push(`  Wholesale:       ${fmt(result.summary.wholesaleCase)} / case`);
  lines.push(`  Consumer Price:  ${fmt(result.summary.srpBottle)} / bottle`);
  lines.push(`                   ${fmt(result.summary.srpCase)} / case`);

  if (result.layerRecaps.length > 0) {
    lines.push('');
    lines.push('Stakeholder Margins');
    for (const recap of result.layerRecaps) {
      lines.push(`  ${recap.label}: ${recap.marginPercent.toFixed(1)}% → ${fmt(recap.grossProfit)} GP / case`);
    }
  }

  if (result.warnings.length > 0) {
    lines.push('');
    lines.push('Warnings');
    for (const w of result.warnings) {
      const icon = w.severity === 'error' ? '!!!' : w.severity === 'warn' ? '!!' : 'i';
      lines.push(`  ${icon} ${w.message}`);
    }
  }

  lines.push('');
  lines.push(`Generated by Wine Pricing Studio • ${new Date().toLocaleDateString()}`);

  return lines.join('\n');
}

/**
 * Copy text to clipboard with fallback for older browsers.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return true;
  }
}
